export const PATHS = {
	last_two: "/home/last-two",
	last_one: "/settings/last-one",
	check: "/home/check",
	blah: "/home/blah",
	ddd: "/home/ddd",
	delete: "/home/delete",
	test4: "/home/test4",
	test_3: "/home/test-3",
	test2: "/home/test2",
	junk: "/home/junk",
  outlines_list: "/home/outlines-list",
  profile: "/settings/profile",
  publishers_list: "/home/publishers-list",
};
